### ISSUE TITLE
Can't build wheel on ubuntu focal

### ISSUE THREAD

**Issue by aptalca** [bigcat88/pillow_heif#14]
Hi,

I was trying to build a wheel for armhf on ubuntu focal and it never completes successfully. Then I tried to build it for amd64 to rule out 32bit related issues and that also fails (with the option `--no-binary pillow_heif`).

The official wheels seem to work, but since there are no wheels for armhf, I have to compile.

I do have the listed build deps `libffi`, `libheif-dev` and `libde265-dev` installed (along with a whole lot of other build deps for other wheels). For reference, I'm using this dockerfile: https://github.com/linuxserver/wheelie/blob/main/Dockerfile

Here's the output of `pip wheel --wheel-dir=/build --no-cache-dir -v --no-binary pillow_heif pillow_heif` on ubuntu focal amd64:
https://pastebin.com/vngx8kqx

Am I missing another build dep? Any ideas?

Thanks

**Comment by bigcat88** [comment]
@aptalca Currently i am sitting at home, cause war started today right in front of my house. And looks like will sit tomorrow and for unknown amount of time more, so I have some time(if there will be internet and electricity)

As I understands you need manylinux2014_i686 wheels for Linux?

**Comment by bigcat88** [comment]
@aptalca 
Can not find python tag in any PEP for arm7 wheels.
For 32 bit Linux I will add wheels in` 0.1.7`

If you need to build it from source easy, I will see, can I tomorrow finishing the integration of PEP 517. If I finished it, it can be built from source just with one command.

**Comment by aptalca** [comment]
> @aptalca Currently i am sitting at home, cause war started today right in front of my house. And looks like will sit tomorrow and for unknown amount of time more, so I have some time(if there will be internet and electricity)

I'm really sorry to hear that. I hope you're safe.

Honestly, armhf is kind of on its way out, with raspbian also finally making their 64bit os a stable release. So it's probably not worth it to push manylinux and musllinux wheels for armhf (not sure if it's even possible as I'm not aware of any other project publishing them for armhf).

All I really need is the ability to install (or build wheels) from source. Then folks on armhf can just do that.

Just so you know, it currently builds from source successfully on alpine, but not on ubuntu.

**Comment by bigcat88** [comment]
@aptalca will see what can I do tomorrow with this, new version will be released in a few days, there will be improvements to building from source for linux.

**Comment by aptalca** [comment]
Sounds good, thanks.

**Comment by aptalca** [comment]
Thanks, 0.1.7 builds from source successfully on ubuntu focal. However it does not build on alpine 3.14. I tried on armhf where there are no official builds and it fails with the following error:
```
Collecting pillow_heif
  Using cached pillow_heif-0.1.7.tar.gz (30.5 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [46 lines of output]
      Cache found for pkg-config
      make: *** No rule to make target 'install'.  Stop.
      Traceback (most recent call last):
        File "/usr/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
          main()
        File "/usr/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/usr/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 164, in prepare_metadata_for_build_wheel
          return hook(metadata_directory, config_settings)
        File "/tmp/pip-build-env-w6oel7_6/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 188, in prepare_metadata_for_build_wheel
          self.run_setup()
        File "/tmp/pip-build-env-w6oel7_6/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 281, in run_setup
          super(_BuildMetaLegacyBackend,
        File "/tmp/pip-build-env-w6oel7_6/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 174, in run_setup
          exec(compile(code, __file__, 'exec'), locals())
        File "setup.py", line 21, in <module>
          setup(
        File "/tmp/pip-build-env-w6oel7_6/overlay/lib/python3.9/site-packages/setuptools/__init__.py", line 155, in setup
          return distutils.core.setup(**attrs)
        File "/tmp/pip-build-env-w6oel7_6/overlay/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 109, in setup
          _setup_distribution = dist = klass(attrs)
        File "/tmp/pip-build-env-w6oel7_6/overlay/lib/python3.9/site-packages/setuptools/dist.py", line 458, in __init__
          _Distribution.__init__(
        File "/tmp/pip-build-env-w6oel7_6/overlay/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 293, in __init__
          self.finalize_options()
        File "/tmp/pip-build-env-w6oel7_6/overlay/lib/python3.9/site-packages/setuptools/dist.py", line 851, in finalize_options
          ep(self)
        File "/tmp/pip-build-env-w6oel7_6/overlay/lib/python3.9/site-packages/setuptools/dist.py", line 872, in _finalize_setup_keywords
          ep.load()(self, ep.name, value)
        File "/tmp/pip-build-env-w6oel7_6/normal/lib/python3.9/site-packages/cffi/setuptools_ext.py", line 219, in cffi_modules
          add_cffi_module(dist, cffi_module)
        File "/tmp/pip-build-env-w6oel7_6/normal/lib/python3.9/site-packages/cffi/setuptools_ext.py", line 49, in add_cffi_module
          execfile(build_file_name, mod_vars)
        File "/tmp/pip-build-env-w6oel7_6/normal/lib/python3.9/site-packages/cffi/setuptools_ext.py", line 25, in execfile
          exec(code, glob, glob)
        File "libheif/build.py", line 28, in <module>
          include_path_prefix = build_libs.build_libs_linux()
        File "/tmp/pip-install-6ai6_tjd/pillow-heif_eaf5bae5a4d543658c1a9fc461c13e84/libheif/build_libs.py", line 168, in build_libs_linux
          build_tools_linux(_is_musllinux)
        File "/tmp/pip-install-6ai6_tjd/pillow-heif_eaf5bae5a4d543658c1a9fc461c13e84/libheif/build_libs.py", line 109, in build_tools_linux
          build_tool_linux(
        File "/tmp/pip-install-6ai6_tjd/pillow-heif_eaf5bae5a4d543658c1a9fc461c13e84/libheif/build_libs.py", line 102, in build_tool_linux
          run("make install".split(), check=True)
        File "/usr/lib/python3.9/subprocess.py", line 528, in run
          raise CalledProcessError(retcode, process.args,
      subprocess.CalledProcessError: Command '['make', 'install']' returned non-zero exit status 2.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by bigcat88** [comment]
@aptalca 
`rm -rf /tmp/pillow_heif`
and post logs with one `-v`
`sudo -H python3 -m pip -v install pillow_heif`
that will speed up process.

Look's like it fails on the first step of building `pkg-config-0.29.2.tar.gz` ...

I will write tomorrow test for building it from source on docker images in github actions.
Spent all day making a reserve internet channel(`tethering iphone to opnsense in qemu`), two days ago due to this war, optic provider get damaged main line, and not able to provide usual wireless internet anymore. But 4G will saves coder's life style. :)

**Comment by aptalca** [comment]
> I will write tomorrow test for building it from source on docker images in github actions.
Spent all day making a reserve internet channel(tethering iphone to opnsense in qemu), two days ago due to this war, optic provider get damaged main line, and not able to provide usual wireless internet anymore. But 4G will saves coder's life style. :)

Ouch, I hope the war ends soon and that you're safe in the meantime.

I just created a test repo with a simple dockerfile here: https://github.com/aptalca/testing-pillow_heif
You can see the github action log where it succeeds on amd64 but fails on arm32v7

I also sent a collaborator invite to the repo so feel free to push and test

**Comment by bigcat88** [comment]
@aptalca Thanks, I will grab after fix that yaml for me. Will see what can be done, why aom is not compiling on arm7. Will reply in a few hours.

**Comment by bigcat88** [comment]
Will change source(probably tomorrow) and if aom is present in system then skip building it.

**Comment by bigcat88** [comment]
@aptalca  by mistake i deleted src release for 0.1.7 from pypi(forgot that pypi don't allow to reupload).
Will upload 0.1.8 today probably, working on it right now.
You free to make pull request for thet yaml and Docker file(name docker file `from_src.Dockerfile` and place in directoy `docker`)

**Comment by bigcat88** [comment]
@aptalca , new version will be released in a week, if nothing bad will happen. 
Is this all and issue can be closed? Or is there something more?

**Comment by aptalca** [comment]
Yup, thanks to your efforts, we were able to publish a Nextcloud mod for mediadc: https://github.com/linuxserver/docker-mods/tree/nextcloud-mediadc
