### ISSUE TITLE
Installation not working properly `Failed to build installable wheels for some pyproject.toml based projects (pillow-heif)`

### ISSUE THREAD

**Issue by erickdcohen** [bigcat88/pillow_heif#287]
### Describe the bug

Attempting to follow [installation instructions](https://pillow-heif.readthedocs.io/en/latest/installation.html) but am met with `ERROR: Failed to build installable wheels for some pyproject.toml based projects (pillow-heif)` 

### Steps/Code to Reproduce

```
python3 -m pip install pillow-heif
```

and tried 

```
pip3 install pillow-heif
```
in a virtual environment

using python 3.10.10

### Expected Results

Successful installation

### Actual Results

```
Collecting pillow-heif
  Using cached pillow_heif-0.18.0.tar.gz (16.2 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: pillow>=10.1.0 in ./.venv/lib/python3.10/site-packages (from pillow-heif) (10.4.0)
Building wheels for collected packages: pillow-heif
  Building wheel for pillow-heif (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for pillow-heif (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [71 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.macosx-11-x86_64-cpython-310
      creating build/lib.macosx-11-x86_64-cpython-310/pillow_heif
      copying pillow_heif/AvifImagePlugin.py -> build/lib.macosx-11-x86_64-cpython-310/pillow_heif
      copying pillow_heif/options.py -> build/lib.macosx-11-x86_64-cpython-310/pillow_heif
      copying pillow_heif/misc.py -> build/lib.macosx-11-x86_64-cpython-310/pillow_heif
      copying pillow_heif/_version.py -> build/lib.macosx-11-x86_64-cpython-310/pillow_heif
      copying pillow_heif/constants.py -> build/lib.macosx-11-x86_64-cpython-310/pillow_heif
      copying pillow_heif/__init__.py -> build/lib.macosx-11-x86_64-cpython-310/pillow_heif
      copying pillow_heif/_lib_info.py -> build/lib.macosx-11-x86_64-cpython-310/pillow_heif
      copying pillow_heif/_deffered_error.py -> build/lib.macosx-11-x86_64-cpython-310/pillow_heif
      copying pillow_heif/heif.py -> build/lib.macosx-11-x86_64-cpython-310/pillow_heif
      copying pillow_heif/as_plugin.py -> build/lib.macosx-11-x86_64-cpython-310/pillow_heif
      copying pillow_heif/HeifImagePlugin.py -> build/lib.macosx-11-x86_64-cpython-310/pillow_heif
      running build_ext
      Package libheif was not found in the pkg-config search path.
      Perhaps you should add the directory containing `libheif.pc'
      to the PKG_CONFIG_PATH environment variable
      No package 'libheif' found
      Package heif was not found in the pkg-config search path.
      Perhaps you should add the directory containing `heif.pc'
      to the PKG_CONFIG_PATH environment variable
      No package 'heif' found
      
      
      The headers or library files could not be found for libheif,
      a required dependency when compiling Pillow-Heif from source.
      
      Please see the install instructions at:
         https://pillow-heif.readthedocs.io/en/latest/installation.html
      
      Looking for `libheif` using pkg-config.
      Looking for `heif` using pkg-config.
      Checking for include file 'heif.h' in '/Users/erickcohen/Documents/code-projects/imageToPdf/.venv/include'
      Checking for include file 'heif.h' in '/Users/erickcohen/Documents/code-projects/imageToPdf/.venv/include/libheif'
      Checking for include file 'heif.h' in '/usr/local/include'
      Checking for include file 'heif.h' in '/usr/local/include/libheif'
      Checking for include file 'heif.h' in '/Library/Developer/CommandLineTools/SDKs/MacOSX12.1.sdk/usr/include'
      Checking for include file 'heif.h' in '/Library/Developer/CommandLineTools/SDKs/MacOSX12.1.sdk/usr/include/libheif'
      Checking for include file 'heif.h' in '/Users/erickcohen/Documents/code-projects/imageToPdf/.venv/include'
      Checking for include file 'heif.h' in '/Users/erickcohen/Documents/code-projects/imageToPdf/.venv/include/libheif'
      Checking for include file 'heif.h' in '/usr/local/opt/python@3.10/Frameworks/Python.framework/Versions/3.10/include/python3.10'
      Checking for include file 'heif.h' in '/usr/local/opt/python@3.10/Frameworks/Python.framework/Versions/3.10/include/python3.10/libheif'
      Traceback (most recent call last):
        File "/Users/erickcohen/Documents/code-projects/imageToPdf/.venv/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Users/erickcohen/Documents/code-projects/imageToPdf/.venv/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/Users/erickcohen/Documents/code-projects/imageToPdf/.venv/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 251, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
        File "/private/var/folders/9d/476pw63113sbsj9w0hkjrt9h0000gn/T/pip-build-env-r2qpkvkt/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 421, in build_wheel
          return self._build_with_temp_dir(
        File "/private/var/folders/9d/476pw63113sbsj9w0hkjrt9h0000gn/T/pip-build-env-r2qpkvkt/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 403, in _build_with_temp_dir
          self.run_setup()
        File "/private/var/folders/9d/476pw63113sbsj9w0hkjrt9h0000gn/T/pip-build-env-r2qpkvkt/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 503, in run_setup
          super().run_setup(setup_script=setup_script)
        File "/private/var/folders/9d/476pw63113sbsj9w0hkjrt9h0000gn/T/pip-build-env-r2qpkvkt/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 318, in run_setup
          exec(code, locals())
        File "<string>", line 288, in <module>
      __main__.RequiredDependencyException:
      
      The headers or library files could not be found for libheif,
      a required dependency when compiling Pillow-Heif from source.
      
      Please see the install instructions at:
         https://pillow-heif.readthedocs.io/en/latest/installation.html
      
      
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pillow-heif
Failed to build pillow-heif
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (pillow-heif)
```

### Versions

```shell
N/A
```

**Comment by bigcat88** [comment]
1. Did you run `brew install x265 libjpeg libde265 libheif` ?
2. What does `brew list libheif` output?
